
POST http://localhost:8002/api/v1/contact
Content-Type: application/json

 {
"id": "1",
"email": "user@email.com",
"phone": "9211234576"
}

###
GET http://localhost:8002/api/v1/contact?id=1

###
GET http://localhost:8002/api/v1/contact/all

###
PATCH http://localhost:8002/api/v1/contact?id=1
Content-Type: application/json

 {
"id": "1",
"email": "admin@email.com",
"phone": "9211234576"
}

###
DELETE http://localhost:8002/api/v1/contact?id=1
